export const Categories = [
  { label: "Arts & Crafts", value: "art_crafts" },
  { label: "Baby & Kids", value: "baby_kids" },
  { label: "Beauty & Personal Care", value: "beauty_personal_care" },
  { label: "Books", value: "books" },
  { label: "Cameras & Photo", value: "camera_photo" },
  { label: "Electronics", value: "electronics" },
  { label: "Events", value: "events" },
  { label: "Food & Beverage", value: "food_beverage" },
  { label: "Health & Wellness", value: "health_wellness" },
  { label: "Home & Living", value: "home_living" },
  { label: "Men's Apparel", value: "men_apparel" },
  { label: "Music", value: "music" },
  { label: "Pets", value: "pets" },
  { label: "Plants & Garden", value: "plats_garden" },
  { label: "Sports", value: "sports" },
  { label: "Tools", value: "tools" },
  { label: "Toys & Games", value: "toys_games" },
  { label: "Travel", value: "travel" },
  { label: "Video Games", value: "video_games" },
  { label: "Women's Apparel", value: "women_Apparel" },
]